{% set name = "Magics" %}
{% set version = "4.5.0" %}

package:
  name: magics-metview
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3473464/{{ name }}-{{ version }}-Source.tar.gz
  sha256: d6f5682772ba7012f845b0c37f7bbaf5e12e6e9cf36da7524b234d8dc073ad2c
  patches:

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true
  run_exports:
    # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements
    - {{ pin_subpackage('magics-metview', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # the CDTs below are needed when building with Metview enabled
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
  host:
    - pkg-config
    - boost
    - expat
    - glib
    - pango
    - cairo
    - proj
    - eccodes
    - libnetcdf
    - jinja2
    - qt
    - zlib
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl
    - xorg-libxfixes  # [linux]
  run:
    - expat
    - pango
    - cairo
    - proj
    - eccodes
    - simplejson
    - libnetcdf
    - qt
    - zlib
  run_constrained:
    # magics-metview is incompatible with magics
    - magics ==9999999999

test:
  commands:
    - printf "%s\n" "${MAGPLUS_HOME:?MAGPLUS_HOME is not set}"
    - which magjsonx
    - test -f $PREFIX/lib/libMagPlus${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlusSingle${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlusDouble${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libMagPlus${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libMagPlusSingle${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libMagPlusDouble${SHLIB_EXT}  # [osx]
about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache-2.0
  license_file:
    - LICENSE_for_source_files
    - COPYING
    - LICENSE

  license_family: Apache
  summary: ECMWF's Meteorological plotting software Magics built with Metview enabled

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
    - sylvielamythepaut
    - iainrussell
